project:
  type: website
  title: "The 'Centre for Research on Ecology, Cognition and Behaviour of Birds' (ECoBird) Lab Guide"

website:
  title: "The 'Centre for Research on Ecology, Cognition and Behaviour of Birds' (ECoBird) Lab Guide"
  page-navigation: true
  
  navbar:
    background: light
    collapse-below: lg
    right:
      - icon: twitter
        href: https://twitter.com/ECoBird_UGent
        aria-label: ECoBird Twitter
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/ecobird-ugent/Lab-guide
          - text: Comments
            url:  https://github.com/ecobird-ugent/Lab-guide/issue

  sidebar:
    style: "docked"
    search: true
    border: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About us
      - section: "Lab Environment"
        contents:
          - file: environment/lab_environment.qmd
            text: Lab environment
          - file: environment/code_of_conduct.qmd
            text: Code of conduct
          - file: environment/communication.qmd
            text: Communication
          - file: environment/meetings.qmd
            text: Lab meetings
          - file: environment/mentoring.qmd
            text: Mentoring
          - file: environment/work_life_balance.qmd
            text: Work/life balance
          - file: environment/working_remotely.qmd
            text: Working remotely
      - href: funding/funding.qmd
        text: Funding and jobs
      - section: "Publications"
        contents:
          - href: publication/addressing_errors.qmd
            text: Addressing errors
          - href: publication/authorship.qmd
            text: Authorship
          - href: publication/conferences.qmd
            text: Conferences
          - href: publication/openaccess.qmd
            text: Open Access 
          - href: publication/public_engagement.qmd
            text: Public engagement
      - section: "Research"
        contents:
          - href: research/copilot.qmd
            text: Copilot system
          - href: research/rdm.qmd
            text: Data management/sharing
          - href: research/facilities.qmd
            text: Facilities
          - href: research/ideas_ip.qmd
            text: Ideas and IP 
          - href: research/network.qmd
            text: Network 
          # - href: research/preg.qmd
          #   text: Transparancy 
          - href: research/support.qmd
            text: Support
        
          
  page-footer: This guide is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

