# About us

Our vision at ECoBird is to promote a deeper understanding of the lives of birds by bridging the gap between ecology, cognitive psychology and behavioural biology. 

Our research spans from the dense canopies of tropical forests to the bustling heart of our cities, aiming to uncover how birds adapt, survive, and thrive in diverse environments. Our research approach is strongly interdisciplinary, at theoretical and methodological level. 

Our center is embedded in the Faculty of Psychology and the Faculty of Sciences (biology & ecology), and we closely collaborate with the Faculty of Veterinary Medicine. Furthermore, we have interdisciplinary collaborations with researchers at other national and international universities, the Research Institute for Nature and Forest (INBO Vlaanderen), and with the [Wildlife Rescue Centre Ostend](https://www.vogelopvangcentrum.be), where our avian research facilities are located.    

The center also aims to be at the forefront of good research practices and Open Science. Where possible and useful, we preregister confirmatory studies and analysis protocols, and share the raw data, code, and experimental materials. Furthermore, we have established a ‘co-pilot system’, whereby members of the research team check e.g., each other’s code or rerun (parts of) the analysis. We hope that these practices can further promote transparency, openness, reproducibility, and scientific integrity.