## Ideas and intellectual property 

### Research ideas and topics

- The lab strongly values team work, and we work together on larger projects. Thus, research ideas are often developed with Dr. Verbruggen and other (senior and junior) team members.  

- When a team member leaves the lab, there is often uncertainty about which ideas are theirs to pursue independently and which must be pursued in collaboration with other lab members.  It is difficult to specify a blanket policy on this issue, as it will depend on many different circumstances.  Lab members are encouraged to discuss this issue openly with Dr. Verbruggen prior to departing the lab, to prevent any misunderstandings. In many cases Dr. Verbruggen will be happy for the (former) lab member to take the ideas and pursue them independently in their new position; this has happened on a number of occasions. In other cases, particularly when the ideas were developed in close collaboration with Dr. Verbruggen, there may be an expectation that further development of the ideas will occur through collaborative efforts.

- Lab members can not claim exclusive ownership over specific research topics, research methods, or study species. All lab members will have the opportunity to work on the topic they find most interesting (but see also the section on [Funding](/funding/funding.qmd)), using the research methods and species that are considered most appropriate. 

### Intellectual property

- As discussed in the section on [data management](/research/rdm.qmd), all data collected within our laboratory is meant to be shared upon submission of the related paper.  In cases where these data can be deidentified they will be shared under a public domain dedication ([CC BY 4](https://creativecommons.org/licenses/by/4.0/)), which 'allows reusers to distribute, remix, adapt, and build upon the material in any medium or format, so long as attribution is given to the creator'. Thus, any researcher can continue to use those data once they leave the lab. In other cases it may be necessary to restrict data sharing (e.g. when the data cannot be deidentified), in which case researchers will need to obtain a data use agreement (see point 4 in the [data sharing](/research/rdm.qmd#data-sharing) section).

- In theory, research data may also be the subject of (technology) transfer efforts by the university as set out in the relevant legislation (cf. codex higher education and general regulation on collaboration and research of the Ghent University Association) if such research data may be suitable for commercialization or – more specifically - if such data may be protected by intellectual property rights. In this case, Dr. Verbruggen will first have to report the research data to the UGent TechTransfer office prior to any further dissemination (publication, presentation, …). 

