## Research network 

The lab is embedded in a strong international and interdisciplinary network. 

- We collaborate with other research labs within the Department of Experimental Psychology and the Faculty of Psychology and Educational Sciences to study various aspects of human behavior, including (but not limited to) cognitive control, impulsivity, and learning. 

- For the long-term Methusalem program (2021-2027; renewable), we work very closely together with Prof. Dr. Luc Lens (the Terrestrial Ecology Unit, UGent) and Prof. Dr. An Martel (Division of Poultry, Exotic Companion, Wildlife and Laboratory Animals at the Faculty of Veterinary Medicine of UGent. 

- Furthermore, the lab can rely on a large multidisciplinary network of international collaborators to provide theoretical and technical input, and to discuss (theoretical and practical) implications of our findings. Examples of such fruitful international collaborations can be found in the publication list of [Dr. Verbruggen](https://biblio.ugent.be/person/801001680884). 

- Lab members are encouraged and supported to expand their own research network. In general, Dr. Verbruggen is more than happy to include external researchers in research projects of the CoBE lab. Lab members wishing to include other researchers in their projects (while working in the CoBE lab) should therefore discuss this with Dr. Verbruggen as well.   
