## Data management and sharing

### Data Management

- Good research data management (RDM) is an integral part of good research practice: it ensures that the data generated by members of the lab is stored securely, can be reused in the future, and can be easily shared between collaborators. It is also an increasingly important part of funder and institutional requirements for open access to research 

- The lab has a detailed [RDM guide](https://github.com/ecobird-ugent/Data-management-guidelines). In this document, lab members will find guidelines on how to manage data and assign roles and responsibilities. The guidelines are largely based on best practice from UGent and the UK Data Archive, but are tailored as far as possible to the needs of ECoBird.

- New team members should read these guidelines carefully when joining the lab. - Lab members can also contact the UGent [RDM support] team (https://www.ugent.be/en/research/datamanagement) for further information and support. 

### Data sharing

- The general lab rule is that data should be as open as possible, as closed as necessary [^6]. See [UGent's RDM support](https://www.ugent.be/en/research/datamanagement/after-research/sharing.htm) website for possible restrictions on data sharing.  

- The FAIR principles [^7] will provide further guidance: data of finished projects should be **F**indable, **A**ccessible, **I**nteroperable (i.e. others should be able to integrate our data with minimal effort), and **R**eusable. 

- Fully anonymised and non-sensitive data will be made publicly available via e.g. the [Open Science Framework](osf.io) and/or other trusted data repositories upon publication at the latest, and preferably upon preprint submission.

- In the case of sensitive data (e.g. personal or otherwise confidential data), the FAIR Principles require that rich metadata should be published to facilitate discovery. Publication of such metadata may also be done via [OSF](osf.io) or other appropriate repositories. This metadata will include clear rules about the process and conditions for accessing the data. In other words, anyone can find out whether the data exists or not, but not everyone will be able or allowed to access and use it (for whatever purpose). In the case of highly sensitive material, or where misuse and abuse is likely, we may need to ask the local ethics committee to arbitrate and decide who gets access and who doesn't. These procedures will allow FAIRness in the absence of FAIR publication of the data itself.

- When full data sets cannot be shared (e.g., due to legal or ethical reasons), we will share at least the processed data necessary to run the primary statistical analyses (assuming these processed data do not contain confidential information either).

- As outlined in the lab's RDM guidelines, public data sets should always include an experiment documentation file, providing all information that is required to interpret the data files. 

- By default, the data will be published under a [CC BY 4.0 licence](https://creativecommons.org/licenses/by/4.0/).


[^6]: Wilkinson, M. D., Dumontier, M., Aalbersberg, Ij. J., Appleton, G., Axton, M., Baak, A., … Mons, B. (2016). The FAIR Guiding Principles for scientific data management and stewardship. Scientific Data, 3, 160018. https://doi.org/10.1038/sdata.2016.18
[^7]: https://www.allea.org/wp-content/uploads/2017/04/ALLEA-European-Code-of-Conduct-for-Research-Integrity-2017.pdf
