## Research support

- Lab members can get research support from dedicated staff within the lab, the department, faculty, and at the central UGent level (e.g, the [data steward team](https://www.ugent.be/en/research/datamanagement/support/data-stewards.htm) for support with RDM requirements). 

- At a lab level, there is a dedicated person responsible for all animal-care related issues at the Wild Life Rescue center. For more general WRC-related issues, Reinoud Allaert will provide additional support. In the past, we have had issues where requests were coming from multiple members of our lab, which was not being sufficiently mindful of time and busy schedules of the support staff. Therefore, in general, you should not directly
contact the lab's support staff with discussing the request first with Dr. Verbruggen. See also the ['communication'](/environment/communication.qmd) section for further guidelines. 

- Our lab is embedded within the [Department of Experimental Psychology](https://www.ugent.be/pp/experimentele-psychologie/en). The department provides formal and informal support at many levels. In general, admin related request can be addressed directly to Lies Baten; technical (computer) related requests should be addressed to Christophe Blankaert; and teaching/marking related requests should be addressed to Vicent Hoofs (see the departmental website for contact details). 

- There is also a departmental Slack channel, which can be useful for informal support requests as well (ranging from research-related questions to questions related to living in Ghent/Belgium etc.). 

- Our team has strong connections with UGent's [Terrestrial Ecology Unit](https://www.ecology.ugent.be/terec/). For some projects, we can also rely on their administative support staff. Importantly, you should not directly
contact the TEREC's support staff with discussing the request first with Dr. Verbruggen and Dr. Lens.

- The Faculty of Psychology and Education Sciences provides all sorts of reseasrch support (e.g., statistical support, technical support, ...). More information and contact details can be found on the webpage of the [Research Support Office](https://www.ugent.be/pp/en/faculty-offices/rso).  