## Mentoring

- I have biweekly individual meetings with all lab members. These individual meetings alternate with the lab meetings. The timing of the meetings is discussed at the beginning of the term. 
- For PhD students, the co-supervisor(s) will also be invited to the individual supervision meetings (if applicable). After each meeting, the PhD students write a short summary of the meeting, which is uploaded to a folder that is accessible to the whole supervision team. 
- I try hard to create a healthy working atmosphere, in which lab members feel comfortable talking about troubling issues. 
- In addition to these 'fixed' bi-weekly meetings, I have an 'open door' policy, meaning that lab members are welcome to ask questions or discuss issues at any time. But for important issues or discussions, it might be advisable to schedule an ad hoc meeting so that there is sufficient time. 
- Once a year, there is also a longer 'developmental meeting', in which we discuss progress for the past year, and both short-term and long-term plans. 


