## Work/life balance

-  We aim to promote sustainable
    creativity and productivity for all of our members, which can’t be
    achieved without a healthy balance between work and personal life.
-  No lab member is expected to
    work in ways that interfere with a healthy life.  Work should not be so
    excessive as to interfere with sleep, exercise, or family/personal
    time.
-  Some lab members (including the PI and co-Is) may work a flexible working pattern, so may send emails out of 'normal' working hours. It is not expected that lab members should respond outside of their own working hours.
-  Lab members are expected to
    be proactive regarding deadlines, to avoid last-minute scrambles.
    Dr. Verbruggen and other lab members may decline to support
    submissions that are prepared with insufficient lead time.
-  We aim to promote an
    environment that is understanding and supportive of individuals with
    child care and adult care responsibilities. This includes but is not
    limited to offering flexible work hours to help individuals with
    familial responsibilities. Ghent University also offers [several services]{https://www.ugent.be/en/ghentuniv/principles/diversity-and-inclusion/for-staff/work-life-balance} in this regard.    
-  The lab is committed to fully
    supporting individuals with chronic physical and/or mental
    illnesses, as well as individuals with accessibility needs. No lab
    member will be discriminated against because of their chronic
    diagnosis or health-related limitations of their ability to work.
    Lab members are encouraged to prioritize their physical and mental
    health as much as possible, and the lab is prepared to support them
    in doing so.
-  Lab members who are seeking
    time off for health (including mental health) reasons are strongly
    encouraged, though absolutely not required, to speak with Dr.
    Verbruggen about their concerns. Dr. Verbruggen commits to approaching
    these conversations in a nonjudgmental and empathetic manner, and to
    working with all lab members to find a solution that works best for
    them.

