## Funding for positions 

### Research assistants and PhD students

- Most Research Assistants and PhD students are (at least initially) funded through existing grants awarded to the PI or collaborators. The work of the PhD students is typically closely aligned with the goals and research aims of the overall project. 
- PhD students can also apply for their own funding. For fellowships from the [Research Foundation - Flanders](https://www.fwo.be/en/fellowships-funding/phd-fellowships/phd-fellowship-fundamental-research/) 
and the [Special Research Fund - Ghent University](https://www.ugent.be/en/research/funding/bof/doc/docen.htm), this can still happen within the first year of the PhD. 
- RA and PhD positions are often advertised, but MSc students interested in doing a PhD are invited to contact Dr. Verbruggen directly. 
Be sure to send your CV, and
    explain in brief your research interests and why you think you would
    be a good fit for the lab.


### How are postdocs in the lab funded?

- Most postdocs in the current lab are
    funded through postdoctoral fellowships or grants that they write
    themselves.  
- Some postdocs can be funded
    through existing grants. In this case, the postdoc must spend a significant portion of
    their time working on that project. The lab will provide
    these postdocs the room to develop their own ideas, but still within the context of the project they are working on.
- Post-doc fellowships are generally not advertised by ourselves, so if you are interested in applying for a fellowship or personal grant within our team, contact Dr. Verbruggen directly. Be sure to send your CV, and
    explain in brief your research interests and why you think you would
    be a good fit for the lab.
- We are particularly
    interested in hiring postdocs who bring diversity to our interdisciplinary team, either
    through their personal identity, research interests or background, or experience. 
    
    
### Programs that have funded COBE (@UGent) PhD students and postdocs

- [Research Foundation - Flanders](https://www.fwo.be/en/) (PhD & post-doc) 
- [Special Research Fund - Ghent University](https://www.ugent.be/en/research/funding/bof/)
- China Scholarship Council (CSC; PhD only). Note: Ghent University has also signed a cooperation agreement with the China Scholarship Council (CSC) to stimulate Ghent University as host institution for Chinese PhD students. More information can be found [here](https://www.ugent.be/en/research/funding/bof/chn)
- [Marie Skłodowska-Curie actions](https://marie-sklodowska-curie-actions.ec.europa.eu)

The lab is currently also supported by an ERC Consolidator grant (European Union’s Horizon 2020 research and innovation program, grant agreement no 769595) and the long-term [Methusalem Program](https://www.ugent.be/en/research/funding/bof/methusalem) (Ghent University, grant BOF.MET.2021.0002.01).
