## Conferences

### Funding and attendence
- The laboratory will generally
fund the attendance of members to at least one conference per year,
pending funding availability. 
  
- While funding is usually tied
    to presenting at the meeting, in some cases the lab will fund
    members to attend who are not presenting, depending on the purpose of the meeting (e.g., are there training opportunities for junior researchers), 
    funding availability, and location of the meeting.
  
- We regularly fund the
    attendance of research assistants to conferences as we think this is
    an essential aspect of their training experience.

- Lab members are encouraged to
find satellite opportunities (such as hackathons or workshops) to
maximize the benefit of their conference travel.

### Abstracts and presentations

- Conference abstract submissions
must be completed at least one week before the final deadline, to allow
coauthors sufficient time to review the submission. 

- Unless otherwise agreed, we use the same authorship guidelines as for research articles. 

- As presentations at conferences also count as 'research output', all lab members should share a pdf of their presentation with Dr. Verbruggen (so that he can then share this with funders -- when required  -- and comply with their funding requirements). Lab members are also encouraged to make a copy of their presentation publicly available (see [Dr. Verbruggen's osf.io page for examples](https://osf.io/72y8z/)).  

- Lab members should acknowledge all relevant funding agencies in their presentations. When in doubt, contact Dr. Verbruggen. 



